- .gitignore
- .idea/vcs.xml
- README.md
- examples/python/benchmark.py
- examples/python/optimizaiton.py
- openjij/__init__.py
- openjij/model.py
- openjij/sampler.py
- openjij/utils.py
- tests/test.py
以下のように分割しました。
Sampler.sampling() -> Sampler.sample_ising()
Sampler.simulated_annealing() -> SASampler.sample_ising()
Sampler.simulated_quantum_annealing() -> SQASampler.sample_ising()
共通部分はBaseSamplerクラスに記述しています。
> change sampler's interface

- CMakeLists.txt
modify CMakeList.txt so that all files are compiled with option fPIC (see #8)
> modify CMakeLists.txt

- src/system/chimera_gpu/chimera_gpu_quantum.cpp
- src/system/chimera_gpu/cuda/kernel.cu
- src/system/cuda_error.h
modify HANDLE_ERROR and change seed in gpu
> modify HANDLE_ERROR and change seed in gpu

- src/system/classical_ising.hpp
* add const to num_spins variable
> add const to num_spins

- openjij/declare.hpp
- src/system/classical_ising.hpp
- src/system/gpu/chimera_gpu_transverse.hpp
- src/system/transverse_ising.hpp
* implement reset_spins in each system module
> implement reset_spins

- src/updater/swendsen_wang.hpp
* modify code so that cast to long-double is available.
> modify swendsen-wang

- openjij/__version.py
- src/system/gpu/chimera_cuda/kernel.cu
- src/system/gpu/chimera_cuda/kernel.hpp
- src/updater/gpu.hpp
- src/updater/single_spin_flip.hpp
- src/updater/swendsen_wang.hpp
* remove dE calculate for each MCS
> remove dE calc for each MCS

- README.md
- openjij/declare.hpp
- openjij/main.cpp
- setup.py
- src/algorithm/all.hpp
- src/result/all.hpp
- src/result/get_solution.hpp
- src/updater/all.hpp
- src/utility/disable_eigen_warning.hpp
- tests/cxxtest.cpp
* disable redundant warning of Eigen.
> disabled eigen redundant warning

- tests/cxxtest.cpp
- tests/test_gpu.py
- tests/test_model.py
- tests/test_sampler.py
- tests/test_sqa.py
* modify tests (c++ and python)
> modify tests

- CMakeLists.txt
- openjij/main.cpp
- src/system/gpu/chimera_cuda/kernel.cu
- tests/test.py
* modify `openjij/main.cpp` for GPU code with double precision.
> modify pybind11 code

- external/eigen.cmake
> fix eigen fetch path

- openjij/declare.hpp
- openjij/main.cpp
- src/system/system.hpp
- src/utility/schedule_list.hpp
* Add classical_constraint_system attribute
> add classical_constraint_system attribute

- src/graph/chimera.hpp
- src/graph/square.hpp
- tests/cxxtest.cpp
* modify json test (chimera graph)
> modify json test

- openjij/sampler/sa_sampler.py
Initialize with sparse graph when the updater is Swendsen-wang
> modify SASampler 

- project_template/Makefile
- project_template/template.cpp
- src/graph/dense.hpp
- src/graph/sparse.hpp
* Fix filepath in project_template.
* add out_of_range exception to `calc_energy` in Dense & Sparse graph.
> fix project_template filepath

- openjij/sampler/csqa_sampler.py
- tests/test_sampler.py
modify csqa_sampler and enable test_csq
> modify csqa_sampler and enable test_csq

- openjij/model/chimera_model.py
- openjij/sampler/sa_sampler.py
* modify sa_sampler and openjij.model
> modify sa_sampler and model

- .gitmodules
- src/graph/cimod/src/binary_quadratic_model.hpp
- src/graph/cimod/src/hash.hpp
- src/graph/cimod/src/utilities.hpp
- src/graph/cimod/src/vartypes.hpp
* remove cimod submodule and place raw files
> remove submodule

- tests/test_model.py
最新版のOpenJijに合わせて、test_model.pyを書き換えました。
2b34289
西村さんの判断による。
> Modigy test_model.py for latest OpenJij

- openjij/sampler/sa_sampler.py
fix `geometric_ising_beta_schedule` in `openjij/sampler/sa_sampler.py`
> modify generating schedule list

- openjij/model/model.py
- tests/test_gpu.py
> fix gpu initialization in model.py

- setup.py
* Add SciPy dependence in setup.py
> add scipy dependence

- README.md
- docs/html/index.html
- openjij/sampler/sqa_sampler.py
- tests/test_sampler.py
* fix README
* add test cases (for schedule)
* fix docs
> last modification for version 0.1.0

- src/graph/cimod/src/binary_polynomial_model.hpp
Improve memory performance of `change_vartype()`
> Modify memory performance of change_vartype()

- .github/dependabot.yml
- .github/workflows/build_and_upolad.yaml
- .github/workflows/build_wheel.yaml
- .github/workflows/ci-test.yml
- CMakeLists.txt
- pyproject.toml
- setup.py
Apple Siliconやlinux/arm64へ対応したビルドを可能にした。
> Adapted to multiple architectures.

- openjij/main.cpp
* add `openjij::` qualifiers to the code in addition to #193
> add openjij::

- setup.py
* `numpy != 1.21.0, != 1.21.1`
> exclude specific versions of numpy

- .github/workflows/build_and_upload.yaml
https://github.com/OpenJij/OpenJij/blob/da702185068bdecdad037b488ed0ba7774d1d35d/.github/workflows/build_and_upload.yaml#L24
> Add setuptools-git-versioning

- .github/workflows/ci-test.yml
- MANIFEST.in
- external/eigen.cmake
- openjij/CMakeLists.txt
- openjij/__init__.py
- openjij/__version.py
- setup.py
- tests/CMakeLists.txt
setup.pyにも一応、setuptools-git-versioningを入れました。
> Change config

- .github/workflows/build_and_upload.yaml
- .github/workflows/ci-test.yml
- setup.py
- Support Python3.10.
- Update cibuildwheel.
> Adopt Python3.10.

- setup.py
* change dimod dependency to `< 0.10.13`
> restrict dimod

- src/system/classical_ising_polynomial.hpp
* Fix bug when calculating the absolute minimum interactions.
* None
On Mac OS 12.2.1, Python 3.9.10
* Befor
```
>>> import openjij as oj
>>> res = oj.SASampler().sample_hubo({(0,0):1e-40, (0,1):1e-40, (0,2):+1}, "BINARY")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.9/site-packages/openjij/sampler/sa_sampler.py", line 380, in sample_hubo
sa_system = cxxjij.system.make_classical_ising_polynomial(_generate_init_state(), model.to_serializable())
RuntimeError: No minimum value in interactions
```
Note that this error may not occur depending on your system.
* After
```
>>> res = oj.SASampler().sample_hubo({(0,0):1e-40, (0,1):1e-40, (0,2):+1}, "BINARY")
>>> res
Response(rec.array([([0, 0, 1], 0., 1)],
dtype=[('sample', 'i1', (3,)), …
```
> Fix bug (find min energy)

- setup.py
An alternative solution (https://github.com/OpenJij/OpenJij/pull/238) is requested.
> Revert "restrict dimod"

- openjij/sampler/sqa_sampler.py
* fix `initial_state` in SQASampler
> fix init_array bug

- setup.py
> Fix OpenMP

- setup.py
- Fix Build Scripts
- Change IMPORT
This Version
`import openjij.cxxjij`
Older Version
`import cxxopenjij`
> For Release

- docs/tutorial/en/003-JijModeling_with_OpenJij.ipynb
- docs/tutorial/en/006-Machine_Learning_by_QA.ipynb
- add English-ver notebooks by @Jacomichi  (currently test version)
- The tutorial is under construction. Just for placing the contents
> add notebooks

- docs/tutorial/ja/001-Introduction.ipynb
- docs/tutorial/ja/002-HuboSolver.ipynb
内容そのものの大幅な変更はありませんが、前のチュートリアルはQUBOの話が後半すぎるのと、章の名前からどこで始まっているかわからないとのことでしたので、
- Ising
- QUBO
- samplerの機能説明
- やや難しい問題
という流れに変更しました。
> OpenJij入門のチュートリアルを追加しました。

- docs/tutorial/ja/008-number_partition.ipynb
最適化計算の例として、数分割問題のチュートリアルを作成し、追加しました。
> 数分割問題のチュートリアルを追加しました

- openjij/sampler/sa_sampler.py
- tests/test_sampler.py
- Allow empty interactions
```python
import openjij as oj
a = oj.SQASampler()
res = a.sample_qubo(Q={})
print(len(res.first.sample))
```
- This code will be merged after https://github.com/OpenJij/cimod/pull/118 is merged and released.
> allow empty case

- openjij/model/model.py
- openjij/sampler/sampler.py
- tests/test_sampler.py
- fix sparse option bug (default spase option is false)
> set default sparse option on

- docs/tutorial/ja/machine_learning/qboost.ipynb
- docs/tutorial/ja/machine_learning/qboost.md
Qboostを用いたOpenJijチュートリアル記事を、新しいJijModelingとtranspilerに対応させています。
https://github.com/Jij-Inc/JijZeptIssues/issues/191
> [新バージョン対応] Qboost

- docs/tutorial/ja/optimization/number_partition.ipynb
- docs/tutorial/ja/optimization/number_partition.md
数分割問題のチュートリアル文章を、最新のJijModeling, JijmodelingTranspilerに対応させました。
https://github.com/Jij-Inc/JijZeptIssues/issues/191
> [新バージョン対応] 数分割問題

- README.md
> READMEにDOIのバッジ追加

- openjij/sampler/sa_sampler.py
- change beta auto setting rule to be more stable.
> change beta rule

- openjij/sampler/sqa_sampler.py
- Please describe changes
- Please describe the related issue for this PR.
- Please note a sample code here if possible.
- Please note if there are destructive changes in this PR.
> fix sqa schedule

- README.md
- openjij/sampler/sqa_sampler.py
Adjust default parameters and update schedule handling to align with version 0.9.2 specifications. Clean up unnecessary code and improve schedule generation logic.
> Fix SQA schedule to revert to version 0.9.2 settings

- .github/workflows/build_and_upload.yaml
> Revert "Bump pypa/cibuildwheel from 2.22.0 to 3.1.2"
